-- PIPELINE_MASTER
-- Schema: REFERENCE
-- Replaces: PIPELINE_CONTROL + LOAD_WATERMARKS + PIPELINE_REGISTRY

-- select * from NEW_TEST.REFERENCE.PIPELINE_MASTER

CREATE OR REPLACE DATABASE NEW_TEST;

CREATE OR REPLACE SCHEMA NEW_TEST.REFERENCE;
CREATE OR REPLACE SCHEMA NEW_TEST.AUDIT;
CREATE OR REPLACE SCHEMA NEW_TEST.BRONZE;
CREATE OR REPLACE SCHEMA NEW_TEST.SILVER;
CREATE OR REPLACE SCHEMA NEW_TEST.GOLD;

-----
CREATE OR REPLACE TABLE NEW_TEST.REFERENCE.PIPELINE_MASTER (
  PIPELINE_ID               VARCHAR(100)    DEFAULT UUID_STRING(),
  PIPELINE_CODE             VARCHAR(100)    NOT NULL,
  PIPELINE_NAME             VARCHAR(200)    NOT NULL,
  ENVIRONMENT               VARCHAR(20)     NOT NULL DEFAULT 'DEV',
  DOMAIN                    VARCHAR(50)     NOT NULL,
  PIPELINE_LAYER            VARCHAR(20)     NOT NULL,
  PIPELINE_TYPE             VARCHAR(30),
  SOURCE_CODE               VARCHAR(50),
  TARGET_TABLE              VARCHAR(200),
  IS_ACTIVE                 BOOLEAN         NOT NULL DEFAULT TRUE,
  INACTIVE_REASON           VARCHAR(500),
  DEACTIVATED_BY            VARCHAR(100),
  DEACTIVATED_AT            TIMESTAMP_NTZ,
  SCHEDULE_TYPE             VARCHAR(30),
  SCHEDULE_CRON             VARCHAR(50),
  SCHEDULE_TIMEZONE         VARCHAR(50)     DEFAULT 'UTC',
  WATERMARK_COLUMN          VARCHAR(100),
  WATERMARK_TYPE            VARCHAR(30),
  WATERMARK_CURRENT         TIMESTAMP_NTZ,
  WATERMARK_LOOKBACK_HRS    NUMBER(5,0)     DEFAULT 0,
  LOAD_TYPE                 VARCHAR(30),
  BATCH_SIZE                NUMBER(10,0)    DEFAULT 10000,
  MAX_ROWS_PER_RUN          NUMBER(38,0),
  EXPECTED_ROW_COUNT        NUMBER(38,0),
  ROW_COUNT_TOLERANCE_PCT   NUMBER(5,2)     DEFAULT 20.00,
  MAX_RETRY_COUNT           NUMBER(5,0)     DEFAULT 3,
  RETRY_BACKOFF_SECS        NUMBER(10,0)    DEFAULT 300,
  RETRY_BACKOFF_TYPE        VARCHAR(20)     DEFAULT 'EXPONENTIAL',
  CURRENT_RETRY_COUNT       NUMBER(5,0)     DEFAULT 0,
  LAST_RETRY_AT             TIMESTAMP_NTZ,
  NOTIFY_ON_SUCCESS         BOOLEAN         DEFAULT FALSE,
  NOTIFY_ON_FAILURE         BOOLEAN         DEFAULT TRUE,
  NOTIFY_ON_WARNING         BOOLEAN         DEFAULT TRUE,
  NOTIFICATION_EMAILS       VARCHAR(1000),
  SLACK_CHANNEL             VARCHAR(100),
  ALERT_PRIORITY            VARCHAR(10)     DEFAULT 'P1',
  DEPENDS_ON_PIPELINES      VARCHAR(1000),
  DEPENDENCY_TIMEOUT_MINS   NUMBER(10,0)    DEFAULT 120,
  COMPONENT_TYPE            VARCHAR(30),
  COMPONENT_NAME            VARCHAR(200),
  DEPENDS_ON_OBJECTS        VARCHAR(1000),
  TASK_NAME                 VARCHAR(200),
  FIA_REFERENCE             VARCHAR(500),
  SCHEMA_VERSION            VARCHAR(20)     DEFAULT 'v1.0',
  OWNER                     VARCHAR(100),
  NOTES                     VARCHAR(2000),
  CREATED_AT                TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY                VARCHAR(100)    DEFAULT CURRENT_USER(),
  UPDATED_AT                TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY                VARCHAR(100)    DEFAULT CURRENT_USER(),
  PRIMARY KEY (PIPELINE_ID),
  UNIQUE (PIPELINE_CODE, ENVIRONMENT)
)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'Master pipeline registry — config, watermark, retry, schedule, notifications';

----

CREATE OR REPLACE TABLE NEW_TEST.AUDIT.PIPELINE_RUN_LOG (
  RUN_ID                VARCHAR(100)    DEFAULT UUID_STRING(),
  BATCH_ID              VARCHAR(100),
  ENVIRONMENT           VARCHAR(20),
  DOMAIN                VARCHAR(50),
  PIPELINE_CODE         VARCHAR(100),
  PIPELINE_LAYER        VARCHAR(20),
  SOURCE_CODE           VARCHAR(50),
  TARGET_TABLE          VARCHAR(200),
  RUN_STATUS            VARCHAR(20)     NOT NULL,
  DQ_CHECK_STATUS       VARCHAR(20),
  RUN_TRIGGER_TYPE      VARCHAR(30),
  RUN_DATE              DATE            DEFAULT CURRENT_DATE(),
  RUN_START_TIME        TIMESTAMP_NTZ,
  RUN_END_TIME          TIMESTAMP_NTZ,
  RUN_DURATION_SECS     NUMBER(38,0),
  ROWS_EXPECTED         NUMBER(38,0),
  ROWS_READ             NUMBER(38,0),
  ROWS_INSERTED         NUMBER(38,0),
  ROWS_UPDATED          NUMBER(38,0),
  ROWS_REJECTED         NUMBER(38,0),
  ROWS_QUARANTINED      NUMBER(38,0),
  TESTS_PASSED          NUMBER(38,0),
  TESTS_FAILED          NUMBER(38,0),
  TESTS_WARNED          NUMBER(38,0),
  WATERMARK_START       TIMESTAMP_NTZ,
  WATERMARK_END         TIMESTAMP_NTZ,
  RETRY_ATTEMPT         NUMBER(5,0)     DEFAULT 0,
  IS_RETRY              BOOLEAN         DEFAULT FALSE,
  RETRY_REASON          VARCHAR(500),
  ERROR_CODE            VARCHAR(50),
  ERROR_MESSAGE         VARCHAR(4000),
  ERROR_STACK_TRACE     VARCHAR(16000),
  SNOWFLAKE_QUERY_ID    VARCHAR(100),
  SNOWFLAKE_TASK_NAME   VARCHAR(200),
  TRIGGERED_BY          VARCHAR(100),
  NOTIFICATION_SENT     BOOLEAN         DEFAULT FALSE,
  NOTIFICATION_AT       TIMESTAMP_NTZ,
  CREATED_AT            TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'Pipeline execution log — all runs all layers all environments';

-- Cluster for query performance
-- MuleSoft polls by RUN_DATE + DOMAIN + PIPELINE_LAYER
ALTER TABLE NEW_TEST.AUDIT.PIPELINE_RUN_LOG
  CLUSTER BY (RUN_DATE, DOMAIN, PIPELINE_LAYER, ENVIRONMENT);

----

CREATE OR REPLACE TABLE NEW_TEST.AUDIT.DQM_CHECK_LOG (
  CHECK_ID              VARCHAR(100)    DEFAULT UUID_STRING(),
  RUN_ID                VARCHAR(100),
  ENVIRONMENT           VARCHAR(20),
  PIPELINE_CODE         VARCHAR(100),
  PIPELINE_LAYER        VARCHAR(20),
  TARGET_TABLE          VARCHAR(200),
  DOMAIN                VARCHAR(50),
  RULE_CODE             VARCHAR(100),
  RULE_NAME             VARCHAR(200),
  RULE_TYPE             VARCHAR(50),
  COLUMN_NAME           VARCHAR(200),
  RULE_EXPRESSION       VARCHAR(4000),
  SEVERITY              VARCHAR(20),
  CHECK_STATUS          VARCHAR(20),
  ROWS_CHECKED          NUMBER(38,0),
  ROWS_PASSED           NUMBER(38,0),
  ROWS_FAILED           NUMBER(38,0),
  ROWS_QUARANTINED      NUMBER(38,0),
  FAILURE_RATE_PCT      NUMBER(10,4),
  VIOLATION_SAMPLE      VARCHAR(4000),
  ACTION_ON_FAIL        VARCHAR(50),
  ACTION_TAKEN          VARCHAR(50),
  QUARANTINE_TABLE      VARCHAR(200),
  EXECUTION_MS          NUMBER(10,0),
  CHECKED_AT            TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'DQ rule execution results — one row per rule per pipeline run';

-- Cluster for query performance
ALTER TABLE NEW_TEST.AUDIT.DQM_CHECK_LOG
  CLUSTER BY (CHECKED_AT::DATE, PIPELINE_CODE, CHECK_STATUS);

----

-- FIX: Added missing opening parenthesis '(' after table name
CREATE OR REPLACE TABLE NEW_TEST.REFERENCE.DQM_RULES (
  RULE_CODE             VARCHAR(100),
  RULE_NAME             VARCHAR(200),
  PIPELINE_CODE         VARCHAR(100),
  PIPELINE_LAYER        VARCHAR(20),
  DOMAIN                VARCHAR(50),
  RULE_TYPE             VARCHAR(50),
  COLUMN_NAME           VARCHAR(200),
  SEVERITY              VARCHAR(20),
  ACTION_ON_FAIL        VARCHAR(50),
  IS_ACTIVE             BOOLEAN         DEFAULT TRUE,
  RULE_EXPRESSION       VARCHAR(4000)
)
COMMENT = 'DQM rules configuration';

-- NOTE: ALTER TABLE below is no longer needed since RULE_EXPRESSION
-- is already included in the CREATE TABLE above. Kept here commented
-- out for reference only.
-- ALTER TABLE NEW_TEST.REFERENCE.DQM_RULES
-- ADD COLUMN IF NOT EXISTS RULE_EXPRESSION VARCHAR(4000);

-------------------------------------------------------------------------NEW_TEST.BRONZE.TEST_TABLE
CREATE OR REPLACE TABLE NEW_TEST.BRONZE.TEST_TABLE (
TEST001              VARCHAR(100),
  TEST002              VARCHAR(100))

  SELECT * from NEW_TEST.BRONZE.TEST_TABLE 