TRUNCATE TABLE NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS;
TRUNCATE TABLE NEW_TEST.BRONZE.STG_VEEVA_CRM_CALLS;
TRUNCATE TABLE NEW_TEST.SILVER.HCP_MASTER;
TRUNCATE TABLE NEW_TEST.GOLD.DIM_HCP;

UPDATE NEW_TEST.REFERENCE.PIPELINE_MASTER
SET WATERMARK_CURRENT = '1900-01-01T00:00:00'::TIMESTAMP_NTZ
WHERE PIPELINE_CODE IN ('VEEVA_CRM_INBOUND', 'SP_SILVER_HCP', 'SP_GOLD_HCP')
AND ENVIRONMENT = 'DEV';

UPDATE NEW_TEST.REFERENCE.PIPELINE_MASTER 
SET CURRENT_RETRY_COUNT = 0,
    TARGET_TABLE = CASE 
      WHEN PIPELINE_CODE = 'SP_SILVER_HCP' THEN 'NEW_TEST.SILVER.HCP_MASTER'
      ELSE TARGET_TABLE
    END,
    MAX_RETRY_COUNT = 3
WHERE ENVIRONMENT = 'DEV';

SELECT 'BRONZE' AS layer, COUNT(*) FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
UNION ALL
SELECT 'STAGE', COUNT(*) FROM NEW_TEST.BRONZE.STG_VEEVA_CRM_CALLS
UNION ALL
SELECT 'SILVER', COUNT(*) FROM NEW_TEST.SILVER.HCP_MASTER
UNION ALL
SELECT 'GOLD', COUNT(*) FROM NEW_TEST.GOLD.DIM_HCP;

SELECT 'BRONZE' AS layer, COUNT(*) FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
UNION ALL SELECT 'SILVER', COUNT(*) FROM NEW_TEST.SILVER.HCP_MASTER
UNION ALL SELECT 'GOLD', COUNT(*) FROM NEW_TEST.GOLD.DIM_HCP;

-- See what MERGE actually did
SELECT CALL_ID, NPI, TERRITORY_CODE, _AUDIT_RUN_ID
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
ORDER BY _AUDIT_LOAD_TS DESC LIMIT 6;

-- Total
SELECT COUNT(*) FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS;

-- Detail per record  
SELECT CALL_ID, TERRITORY_CODE, CALL_TYPE, SAMPLE_UNITS, 
       _AUDIT_RUN_ID, _AUDIT_LOAD_TS::VARCHAR
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
WHERE CALL_ID IN ('DEMO004', 'DEMO005', 'DEMO007')
ORDER BY CALL_ID;

-- Total
SELECT COUNT(*) FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS;

-- Check if DEMO004's hash matches what stage would produce
SELECT 
  CALL_ID,
  TERRITORY_CODE,
  CALL_TYPE,
  SAMPLE_UNITS,
  _AUDIT_ROW_HASH AS stored_hash,
  SHA2(
    COALESCE(NPI, '') || '|' ||
    COALESCE(TERRITORY_CODE, '') || '|' ||
    COALESCE(REP_ID, '') || '|' ||
    COALESCE(CALL_DATE::VARCHAR, '') || '|' ||
    COALESCE(PRODUCT_CODE, '') || '|' ||
    COALESCE(CALL_TYPE, '') || '|' ||
    COALESCE(CALL_OUTCOME, '') || '|' ||
    COALESCE(SAMPLE_UNITS::VARCHAR, '') || '|' ||
    COALESCE(NOTES, ''),
    256
  ) AS recomputed_hash,
  CASE 
    WHEN _AUDIT_ROW_HASH = SHA2(
      COALESCE(NPI, '') || '|' || COALESCE(TERRITORY_CODE, '') || '|' ||
      COALESCE(REP_ID, '') || '|' || COALESCE(CALL_DATE::VARCHAR, '') || '|' ||
      COALESCE(PRODUCT_CODE, '') || '|' || COALESCE(CALL_TYPE, '') || '|' ||
      COALESCE(CALL_OUTCOME, '') || '|' || COALESCE(SAMPLE_UNITS::VARCHAR, '') || '|' ||
      COALESCE(NOTES, ''), 256)
    THEN 'MATCH' 
    ELSE 'DIFFER' 
  END AS verdict
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
WHERE CALL_ID = 'DEMO004';

SELECT 
  'BRONZE' AS source, CALL_ID, NPI, TERRITORY_CODE, CALL_TYPE,
  CALL_OUTCOME, SAMPLE_UNITS, NOTES, _AUDIT_ROW_HASH
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
WHERE CALL_ID = 'DEMO004';

SELECT * FROM NEW_TEST.AUDIT.DQM_CHECK_LOG

SELECT * FROM NEW_TEST
SELECT * FROM NEW_TEST.REFERENCE.PIPELINE_MASTER

----------------------------------------------------
USE ROLE ACCOUNTADMIN;
USE DATABASE NEW_TEST;
USE SCHEMA AUDIT;

-- Update existing secret with GitHub credentials
CREATE OR REPLACE SECRET github_secret
  TYPE = password
  USERNAME = 'Praveen946-PS'
  PASSWORD = 'BPraveen946$';

-- Create new API integration for GitHub
CREATE OR REPLACE API INTEGRATION github_api
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/Praveen946-PS/')
  ALLOWED_AUTHENTICATION_SECRETS = (github_secret)
  ENABLED = TRUE;

-- Test the connection
CREATE OR REPLACE GIT REPOSITORY github_test
  API_INTEGRATION = github_api
  GIT_CREDENTIALS = github_secret
  ORIGIN = 'https://github.com/Praveen946-PS/Demo_SF.git';

ALTER GIT REPOSITORY github_test FETCH;

//https://github.com/Praveen946-PS/Demo_SF.git

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE API INTEGRATION github_api
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/Praveen946-PS/')
  ALLOWED_AUTHENTICATION_SECRETS = (NEW_TEST.AUDIT.github_secret)
  ENABLED = TRUE;

  USE ROLE ACCOUNTADMIN;

SHOW API INTEGRATIONS LIKE 'GITHUB_API';